#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Apr 10 20:18:39 EEST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto d7a2098513044e6eb80bfc71f507d00a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot carry_look_ahead_16bits_sim_behav xil_defaultlib.carry_look_ahead_16bits_sim xil_defaultlib.glbl -log elaborate.log"
xelab -wto d7a2098513044e6eb80bfc71f507d00a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot carry_look_ahead_16bits_sim_behav xil_defaultlib.carry_look_ahead_16bits_sim xil_defaultlib.glbl -log elaborate.log

